language: python
python:
 - "3.6"
install:
 - pip install codecov
 - pip install coveralls
 - pip install -r requirements.txt
script:
 - coverage run --source steampi setup.py test
after_success:
 - coveralls
 - codecov